title: Benjamin Culmer
description: Website to display my college work
theme: jekyll-theme-cayman
markdown: kramdown
highlighter: rouge

production_url: https://benjamin-culmer.github.io
github: [metadata]
